// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {PoseidonT3} from "./PoseidonT3.sol";

/// @notice Groth16 verifier for the Akmena private-pool withdrawal circuit.
/// @dev Generated by snarkjs from withdraw.circom. Verifies a proof of:
///      1. Knowledge of (nullifier, secret) for a commitment in the Merkle tree
///      2. Correct nullifier derivation: nullifierHash = Poseidon(nullifier)
///      3. Merkle membership against a known root
///      Public signals: [root, nullifierHash, recipient, relayer, fee]
///      (recipient/relayer/fee are proof-bound; tampering invalidates the proof)
interface IWithdrawVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[5] calldata _pubSignals
    ) external returns (bool);
}

/// @title AkmenaPrivatePool
/// @notice Fixed-denomination zero-knowledge private pool for AI-agent commerce.
///
/// @dev Design (see PRIVACY_V2_DESIGN.md):
///      - Deposits: fixed DENOMINATION, commitment = Poseidon(nullifier, secret)
///        inserted into an incremental Merkle tree (depth 20, ~1M leaves).
///      - Withdrawals: Groth16 proof of Merkle membership + nullifier correctness.
///        The proof reveals ONLY: nullifierHash, root, recipient, relayer, fee.
///        It hides: which deposit, nullifier, secret.
///      - Nullifiers prevent double-spend without linking to deposits.
///      - Relayers enable gas abstraction: the recipient needs no native token.
///      - Root history (100) lets proofs survive block delays between proving
///        and mining.
///
///      Privacy properties (vs the v1 hash-preimage design):
///      - v1 revealed the full commitment preimage at settlement: unlinkability = 0.
///      - v2 reveals nothing linking withdrawal to deposit beyond the
///        anonymity set (all deposits in this denomination pool).
///
///      What this does NOT hide: deposit timing/amount (fixed denom mitigates),
///      withdrawal timing, recipient address (use stealth addresses for that).
///      Viewing keys / association sets are future extensions.
contract AkmenaPrivatePool {
    // ---------------------------------------------------------------------
    // Constants
    // ---------------------------------------------------------------------

    uint256 public constant TREE_DEPTH = 20;
    uint256 public constant ROOT_HISTORY_SIZE = 100;

    // ---------------------------------------------------------------------
    // Immutables
    // ---------------------------------------------------------------------

    /// @notice Fixed deposit/withdrawal amount for this pool.
    uint256 public immutable DENOMINATION;
    /// @notice Groth16 verifier for the withdrawal circuit.
    IWithdrawVerifier public immutable VERIFIER;

    // ---------------------------------------------------------------------
    // Merkle tree state
    // ---------------------------------------------------------------------

    /// @notice Subtree hashes for incremental insertion.
    bytes32[TREE_DEPTH] public filledSubtrees;
    /// @notice Zero hashes per level (hash of empty subtree).
    bytes32[TREE_DEPTH] public zeros;
    /// @notice Current tree root.
    bytes32 public currentRoot;
    /// @notice Ring buffer of recent roots for proof validity across delays.
    bytes32[ROOT_HISTORY_SIZE] public roots;
    uint32 public currentRootIndex;
    /// @notice Next leaf index (= number of deposits).
    uint32 public nextLeafIndex;

    // ---------------------------------------------------------------------
    // Nullifiers
    // ---------------------------------------------------------------------

    /// @notice Spent nullifier hashes (double-spend prevention).
    mapping(bytes32 => bool) public nullifierHashes;

    // ---------------------------------------------------------------------
    // Events & errors
    // ---------------------------------------------------------------------

    event Deposit(bytes32 indexed commitment, uint32 indexed leafIndex, uint256 timestamp);
    event Withdrawal(
        address indexed recipient, bytes32 indexed nullifierHash, address indexed relayer, uint256 fee
    );

    error IncorrectDenomination();
    error UnknownRoot();
    error NullifierAlreadySpent();
    error InvalidProof();
    error FeeExceedsDenomination();
    error TransferFailed();

    // ---------------------------------------------------------------------
    // Constructor
    // ---------------------------------------------------------------------

    constructor(IWithdrawVerifier _verifier, uint256 _denomination) {
        VERIFIER = _verifier;
        DENOMINATION = _denomination;

        // Compute zero hashes: zeros[0] = Poseidon(0,0),
        // zeros[i] = Poseidon(zeros[i-1], zeros[i-1]).
        bytes32 currentZero = bytes32(PoseidonT3.hash([uint256(0), uint256(0)]));
        zeros[0] = currentZero;
        filledSubtrees[0] = currentZero;
        for (uint256 i = 1; i < TREE_DEPTH; i++) {
            currentZero = bytes32(
                PoseidonT3.hash([uint256(currentZero), uint256(currentZero)])
            );
            zeros[i] = currentZero;
            filledSubtrees[i] = currentZero;
        }

        currentRoot = currentZero;
        roots[0] = currentZero;
    }

    // ---------------------------------------------------------------------
    // Deposits
    // ---------------------------------------------------------------------

    /// @notice Deposit exactly DENOMINATION with a Poseidon commitment.
    /// @param _commitment Poseidon(nullifier, secret), computed off-chain.
    ///        The nullifier and secret must NEVER touch the chain.
    function deposit(bytes32 _commitment) external payable {
        if (msg.value != DENOMINATION) revert IncorrectDenomination();

        uint32 leafIndex = nextLeafIndex;
        _insert(_commitment, leafIndex);
        nextLeafIndex = leafIndex + 1;

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    /// @notice Insert a leaf into the incremental Merkle tree.
    function _insert(bytes32 _leaf, uint32 _leafIndex) internal {
        bytes32 currentHash = _leaf;
        uint32 currentIndex = _leafIndex;

        for (uint256 i = 0; i < TREE_DEPTH; i++) {
            if (currentIndex % 2 == 0) {
                filledSubtrees[i] = currentHash;
                currentHash = bytes32(
                    PoseidonT3.hash([uint256(currentHash), uint256(zeros[i])])
                );
            } else {
                currentHash = bytes32(
                    PoseidonT3.hash([uint256(filledSubtrees[i]), uint256(currentHash)])
                );
            }
            currentIndex /= 2;
        }

        currentRoot = currentHash;
        currentRootIndex = (currentRootIndex + 1) % uint32(ROOT_HISTORY_SIZE);
        roots[currentRootIndex] = currentHash;
    }

    /// @notice Check whether a root is in the recent history.
    function isKnownRoot(bytes32 _root) public view returns (bool) {
        if (_root == bytes32(0)) return false;
        // Check current root first (common case), then history.
        if (_root == currentRoot) return true;
        for (uint256 i = 0; i < ROOT_HISTORY_SIZE; i++) {
            if (roots[i] == _root) return true;
        }
        return false;
    }

    // ---------------------------------------------------------------------
    // Withdrawals
    // ---------------------------------------------------------------------

    /// @notice Withdraw by revealing a nullifier and a ZK membership proof.
    /// @param _pA Groth16 proof point A.
    /// @param _pB Groth16 proof point B.
    /// @param _pC Groth16 proof point C.
    /// @param _root Merkle root the proof was generated against (must be known).
    /// @param _nullifierHash Poseidon(nullifier); marked spent.
    /// @param _recipient Destination for DENOMINATION - fee.
    /// @param _relayer Relayer submitting the tx (may be address(0) for self-relay).
    /// @param _fee Relayer fee, taken from the denomination (proof-bound).
    function withdraw(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        bytes32 _root,
        bytes32 _nullifierHash,
        address payable _recipient,
        address payable _relayer,
        uint256 _fee
    ) external {
        if (_fee > DENOMINATION) revert FeeExceedsDenomination();
        if (nullifierHashes[_nullifierHash]) revert NullifierAlreadySpent();
        if (!isKnownRoot(_root)) revert UnknownRoot();

        // Public signals: [root, nullifierHash, recipient, relayer, fee].
        // The proof binds recipient/relayer/fee: a relayer cannot redirect
        // funds or inflate the fee without invalidating the proof.
        uint256[5] memory pubSignals = [
            uint256(_root),
            uint256(_nullifierHash),
            uint256(uint160(address(_recipient))),
            uint256(uint160(address(_relayer))),
            _fee
        ];
        if (!VERIFIER.verifyProof(_pA, _pB, _pC, pubSignals)) revert InvalidProof();

        nullifierHashes[_nullifierHash] = true;

        emit Withdrawal(_recipient, _nullifierHash, _relayer, _fee);

        // Effects before interactions: nullifier marked spent above.
        uint256 recipientAmount = DENOMINATION - _fee;
        if (recipientAmount > 0) {
            (bool okR,) = _recipient.call{value: recipientAmount}("");
            if (!okR) revert TransferFailed();
        }
        if (_fee > 0) {
            (bool okF,) = _relayer.call{value: _fee}("");
            if (!okF) revert TransferFailed();
        }
    }

    /// @notice Number of deposits in the pool (= anonymity set size).
    function anonymitySetSize() external view returns (uint32) {
        return nextLeafIndex;
    }
}
